---
kind: pipeline
type: docker
name: localstack-ci

trigger:
  event:
    - push
    - pull_request
    - custom
  branch:
    - main

services:
  - name: localstack
    image: localstack/localstack
    #environment:
    #  LOCALSTACK_API_KEY:
    #    from_secret: localstack_api_key

environment:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: eu-west-1

steps:
  - name: init
    image: alpine/curl:3.14
    commands:
      - until curl -s http://localstack:4566/_localstack/health; do echo -n . && sleep 1; done

  - name: deploy
    image: hashicorp/terraform:1.5.3
    commands:
      - terraform fmt
      - terraform init -backend=false -upgrade -lock=false
      - terraform validate
      - terraform plan -lock=false -input=false -var-file fixtures.tfvars
      - terraform apply -input=true -auto-approve
  
  - name: tf show
    image: hashicorp/terraform:1.5.3
    commands:
      - terraform state list
      - terraform show

  - name: integration test
    image: amazon/aws-cli
    commands:
      - --endpoint-url=http://localstack:4566 s3 ls

